In [6]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [7]:
l = [5,4,1,6,6,1,3,67,7,8,9]

In [8]:
sum(l)

117

In [9]:
l +[5]

[5, 4, 1, 6, 6, 1, 3, 67, 7, 8, 9, 5]

In [13]:
l + ["no", "no", "no existe"]

[5, 4, 1, 6, 6, 1, 3, 67, 7, 8, 9, 'no', 'no', 'no existe']

In [14]:
a = np.array(l)

In [15]:
a

array([ 5,  4,  1,  6,  6,  1,  3, 67,  7,  8,  9])

In [16]:
type(a)

numpy.ndarray

In [17]:
a.dtype

dtype('int64')

In [19]:
type(5)

int

In [20]:
%time
map(lambda x: x + 5, l)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.15 µs


[10, 9, 6, 11, 11, 6, 8, 72, 12, 13, 14]

In [21]:
%time
l2 = []
for x in l:
    l2.append(x+5)
l2

CPU times: user 1 µs, sys: 1 µs, total: 2 µs
Wall time: 4.05 µs


[10, 9, 6, 11, 11, 6, 8, 72, 12, 13, 14]

In [22]:
%time
[x+5 for x in l]

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.15 µs


[10, 9, 6, 11, 11, 6, 8, 72, 12, 13, 14]

In [23]:
l = xrange(10000)


In [24]:
l = [12,4,5,1,3,6,8,2,3,6,87,2]

In [25]:
len(l)

12

In [29]:
a = np.array(l)

In [30]:
a.reshape(3,4)

array([[12,  4,  5,  1],
       [ 3,  6,  8,  2],
       [ 3,  6, 87,  2]])

In [31]:
m = a.reshape(3,4)

In [32]:
m.transpose()

array([[12,  3,  3],
       [ 4,  6,  6],
       [ 5,  8, 87],
       [ 1,  2,  2]])

In [33]:
m*m

array([[ 144,   16,   25,    1],
       [   9,   36,   64,    4],
       [   9,   36, 7569,    4]])

In [36]:
m.dot(m.transpose())

array([[ 186,  102,  497],
       [ 102,  113,  745],
       [ 497,  745, 7618]])

In [37]:
m + m

array([[ 24,   8,  10,   2],
       [  6,  12,  16,   4],
       [  6,  12, 174,   4]])

In [39]:
m[1,2]

8

In [40]:
m[:,0]

array([12,  3,  3])

In [41]:
m[0,:].shape

(4,)

In [42]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
np.eye(3,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

In [44]:
import numpy.linalg as la

In [45]:
la.eig(m[0:2,0:2])

(array([ 13.58257569,   4.41742431]), array([[ 0.92986687, -0.4665839 ],
        [ 0.36789618,  0.88447694]]))

In [46]:
c = m[0:3,0:3]

In [47]:
c

array([[12,  4,  5],
       [ 3,  6,  8],
       [ 3,  6, 87]])

In [48]:
la.inv(c)

array([[ 0.1       , -0.06708861,  0.00042194],
       [-0.05      ,  0.21708861, -0.01708861],
       [ 0.        , -0.01265823,  0.01265823]])

In [49]:
la.inv(c).dot(c)

array([[  1.00000000e+00,  -1.38777878e-17,  -3.46944695e-17],
       [ -1.73472348e-16,   1.00000000e+00,  -2.22044605e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [50]:
c

array([[12,  4,  5],
       [ 3,  6,  8],
       [ 3,  6, 87]])

In [52]:
c>3

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [53]:
c[c>3] 

array([12,  4,  5,  6,  8,  6, 87])

In [54]:
np.where(c>3)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 1, 2, 1, 2]))

In [64]:
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.0061995972313
0.998187045321


In [87]:
a = np.arange(11)
a[(a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])